# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
excerpt_link: More
fancybox: true

# Sidebar
#sidebar: bottom
#widgets:
#- recent_posts
#- tagcloud 
#- archive
#- related_posts

# Miscellaneous
google_analytics: UA-115542258-1 
favicon: /favicon.ico
twitter: bitsbobsbytes 
google_plus:
fb_admins:
fb_app_id:
